# Site settings
# このファイルはdocker compose up やりなおさないとできない
title: What's up! ayaponzuです！
navtitle: What's up!
email: ayaponzu200525@gmail.com
# GitHub Pages用のURLを設定
url: "https://ayaponzu2525.github.io"
# baseurlを追加（リポジトリ名がユーザー名と同じ場合は空文字）
baseurl: ""
description: "ソフトウェアエンジニア志望の専門学生のポートフォリオサイト IT系専門学生"
keywords: "your keywords, separated by commas"
programskills: "Python・C・C++・C#・HTML・CSS・Javascript・PHP"
skills: "AI・電気工事"
hobby: "guitar - tennis - game"
meta_author: LastName FirstName

# 以下は変更なし
google_verify:
bing_verify:
contact: static
disqus_shortname: myshortname

# Color settings
color:
  primary: "18bc9c" # 先頭にクォートを追加
  primary-rgb: "24,288,156"
  secondary: "2c3e50" # 先頭にクォートを追加
  secondary-dark: "233140" # 先頭にクォートを追加

# 以下は変更なし
footer:
  copyright: ayaponzu
  location: Japan
  social: Around the Web
  credits: Credits

social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: "https://github.com/ayaponzu2525"

address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# 以下を追加
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""